window.VOCAB_EXTRA_ENRICHMENTS = (() => {
  const entries = [
    ["A as well as B", "這項提案包含時程，也包含預算。", "along with, together with", "B only, without A"],
    ["A be followed by B", "簡報之後會接著一段簡短的問答時間。", "come after, be succeeded by", "be preceded by, come before"],
    ["A and B alike", "經理和實習生都參加了工作坊。", "both A and B, A together with B", "neither A nor B, A but not B"],
    ["a complete line of", "這家店提供完整系列的辦公家具。", "a full range of, a whole set of", "a limited line of, a partial range of"],
    ["a copy of", "請寄一份發票副本給會計部。", "a duplicate of, a reproduction of", "the original, no copy"],
    ["a couple of", "我們需要幾張椅子給會議室使用。", "a few, two or three", "none, many"],
    ["a glass of", "她在研討會前點了一杯水。", "one cup of, one serving of", "an empty glass, no drink"],
    ["a great deal", "這項新政策幫了很大的忙。", "a lot, considerably", "little, hardly at all"],
    ["a great deal of", "這個專案需要大量規劃。", "a large amount of, plenty of", "little, a small amount of"],
    ["a large attendance", "今年的會議有很多人出席。", "a big turnout, a high attendance", "low attendance, poor turnout"],
    ["a letter of gratitude", "他寫了一封感謝信給志工們。", "thank-you letter, appreciation letter", "complaint letter, critical letter"],
    ["a loaf of", "她在回家路上買了一條麵包。", "one loaf, a whole bread", "a slice of, a piece of"],
    ["a number of", "許多員工要求接受訓練。", "several, many", "few, none"],
    ["a piece of equipment", "技術人員檢查了每一件設備。", "a device, a machine", "a set of equipment, no equipment"],
    ["a range of", "這家飯店為客人提供一系列服務。", "a variety of, an array of", "a single type of, a narrow range of"],
    ["a selection of", "這本型錄包含一組精選筆記型電腦。", "a choice of, an assortment of", "a single option, no selection"],
    ["a series of", "經理安排了一連串面試。", "a sequence of, a succession of", "one single, an isolated"],
    ["a sheet of", "請在每張桌上放一張紙。", "one page of, one piece of", "a stack of, no sheet"],
    ["a string of", "團隊慶祝一連串成功的上市活動。", "a series of, a chain of", "one isolated, a break in"],
    ["a variety of", "自助餐提供各種健康選擇。", "various, many kinds of", "one kind of, uniform"],
    ["various", "各部門都參加了預算會議。", "different, diverse", "same, uniform"],
    ["abandon", "公司沒有放棄擴張計畫。", "give up, desert", "continue, keep"],
    ["abate", "大雨在中午前開始減弱。", "lessen, subside", "increase, intensify"],
    ["abbreviate", "你可以在表格上縮寫部門名稱。", "shorten, condense", "extend, spell out"],
    ["ability", "她解決問題的能力讓客戶印象深刻。", "skill, capability", "inability, weakness"],
    ["aboard", "乘客必須在早上八點前登上火車。", "on board, on", "ashore, off"],
    ["abolish", "市政府計畫廢除過時的費用。", "eliminate, cancel", "establish, introduce"],
    ["abridgment", "編輯準備了這份報告的刪節版。", "summary, shortened version", "full version, expansion"],
    ["abruptly", "公告之後會議突然結束。", "suddenly, unexpectedly", "gradually, smoothly"],
    ["absence", "請提前通知人資任何缺席情況。", "nonattendance, lack", "presence, attendance"],
    ["absolute", "這個期限是絕對的，不能更改。", "complete, definite", "relative, limited"],
    ["absolutely", "這些數字完全正確。", "completely, definitely", "partly, somewhat"],
    ["absorbing", "這支訓練影片出乎意料地吸引人。", "engaging, fascinating", "boring, dull"],
    ["abstract", "這篇文章以一段簡短摘要開頭。", "summary, conceptual", "concrete, detailed text"],
    ["abundant", "這個地區有豐富的自然資源。", "plentiful, ample", "scarce, limited"],
    ["abundantly", "這本手冊把好處說得非常清楚。", "plentifully, clearly", "scarcely, barely"],
    ["abuse", "員工不應該濫用公司資源。", "misuse, mistreat", "use properly, protect"],
    ["accelerate", "新軟體會加速訂單處理。", "speed up, hasten", "slow down, delay"],
    ["accept", "我們接受信用卡付款。", "receive, approve", "reject, refuse"],
    ["accept an award", "這位設計師將在典禮上接受獎項。", "receive a prize, take an award", "decline an award, refuse a prize"],
    ["accept the offer", "她決定接受那家公司提出的條件。", "agree to the offer, take the offer", "reject the offer, turn down the offer"],
    ["acceptable", "你修改後的時程對客戶來說可以接受。", "satisfactory, allowable", "unacceptable, unsuitable"],
    ["access", "只有員工可以存取資料庫。", "enter, use", "block, deny"],
    ["access road", "卡車應該使用倉庫後方的進出道路。", "entry road, service road", "blocked road, closed road"],
    ["access to", "所有會員都能使用線上圖書館。", "use of, entry to", "no access to, exclusion from"],
    ["accessibility", "整修工程改善了車站的便利性。", "availability, ease of access", "inaccessibility, difficulty"],
    ["accessible", "這些檔案可以透過共用雲端硬碟取得。", "available, reachable", "inaccessible, unavailable"],
    ["accidentally", "我不小心刪除了那封舊訊息。", "by chance, unintentionally", "deliberately, intentionally"],
    ["acclaim", "這項產品獲得業界專家的讚譽。", "praise, approval", "criticism, blame"],
    ["accommodate", "這家飯店最多可容納三百位客人。", "hold, house", "turn away, reject"],
    ["accommodation", "公司為來訪員工安排住宿。", "lodging, housing", "eviction, lack of lodging"],
    ["accompany", "導遊會在旅程中陪同客人。", "escort, go with", "leave, separate from"],
    ["accomplish", "我們可以在星期五前完成這項任務。", "complete, achieve", "fail, leave unfinished"],
    ["accomplished", "她是一位熟練的公開演說者。", "skilled, talented", "inexperienced, unskilled"],
    ["accomplishment", "完成這個專案是一項重大成就。", "achievement, success", "failure, defeat"],
    ["accordance", "所有退款都會依照公司政策處理。", "compliance, conformity", "violation, disagreement"],
    ["accordingly", "需求增加，因此價格也相應上漲。", "therefore, consequently", "regardless, nevertheless"],
    ["according to", "根據報告，四月銷售有所改善。", "based on, as stated by", "contrary to, regardless of"],
    ["account", "請更新你的帳戶資料。", "record, account profile", "cash payment, no account"],
    ["account payable", "會計在付款前檢查每一筆應付帳款。", "payable account, debt owed", "account receivable, prepaid asset"],
    ["accountable", "團隊主管要對最終結果負責。", "responsible, answerable", "unaccountable, irresponsible"],
    ["accountant", "會計人員準備了季度報告。", "bookkeeper, auditor", "client, nonaccountant"],
    ["accounting", "她在會計部工作。", "bookkeeping, financial reporting", "nonfinancial work, sales"],
    ["accredit", "這個機構將認可這項訓練課程。", "certify, authorize", "discredit, reject"],
    ["accrue", "利息會從購買日期開始累積。", "accumulate, build up", "decrease, diminish"],
    ["accumulate", "出差期間收據很快就會累積起來。", "collect, gather", "disperse, reduce"],
    ["accuracy", "請檢查這些數字的準確性。", "precision, correctness", "inaccuracy, error"],
    ["accurate", "調查結果是準確的。", "correct, precise", "inaccurate, wrong"],
    ["accurately", "系統會準確記錄出勤。", "precisely, correctly", "inaccurately, incorrectly"],
    ["accuse", "顧客沒有直接指控任何人。", "charge, blame", "defend, excuse"],
    ["accumulation", "電子郵件的累積拖慢了回覆速度。", "buildup, collection", "reduction, decrease"],
    ["accustomed", "新員工很快就習慣了這個時程。", "used to, familiar with", "unaccustomed, unfamiliar"],
    ["achievable", "這個銷售目標具有挑戰性，但可以達成。", "attainable, reachable", "impossible, unattainable"],
    ["achieve", "團隊希望本季達成創紀錄銷售。", "attain, accomplish", "fail, miss"],
    ["achieve one's goal", "規律練習幫助她達成目標。", "reach one's goal, accomplish one's aim", "miss one's goal, fall short"],
    ["achievement", "這個獎項表彰他在行銷方面的成就。", "accomplishment, success", "failure, setback"],
    ["achiever", "這項獎學金是為高成就者設計的。", "high performer, successful person", "underachiever, nonachiever"],
    ["acknowledge", "請確認已收到這封電子郵件。", "confirm, admit", "deny, ignore"],
    ["acquaint", "新生訓練會讓實習生熟悉辦公室規則。", "familiarize, inform", "hide from, keep unaware"],
    ["acquaintance", "我在商展遇到一位老熟人。", "contact, familiar person", "stranger, close friend"],
    ["acquire", "這家公司計畫收購一家較小的競爭者。", "obtain, purchase", "lose, give up"],
    ["acquired", "他後天取得的技能幫助他轉換職涯。", "obtained, learned", "inborn, natural"],
    ["acquisition", "這次收購擴大了公司的產品線。", "purchase, takeover", "sale, loss"],
    ["across from", "銀行在郵局對面。", "opposite, facing", "next to, beside"],
    ["across the street", "街道對面開了一家新咖啡館。", "on the other side of the street, opposite", "on the same side, next door"],
    ["act", "主管在緊急情況下必須迅速行動。", "do, take action", "wait, remain inactive"],
    ["acting", "代理主任批准了這項請求。", "temporary, interim", "permanent, official"],
    ["activate", "使用這組代碼啟用你的帳戶。", "turn on, enable", "deactivate, disable"],
    ["active", "她仍積極參與當地商業團體。", "energetic, involved", "inactive, passive"],
    ["actually", "這次維修實際上不到一小時就完成了。", "in fact, really", "supposedly, apparently"],
    ["acute", "工廠面臨嚴重的工人短缺。", "severe, intense", "minor, mild"],
    ["adapt", "團隊必須適應新系統。", "adjust, modify", "resist, remain unchanged"],
    ["adaptability", "適應能力在變動的職場中很有價值。", "flexibility, adjustability", "rigidity, inflexibility"],
    ["adaptable", "這套軟體能適用於不同產業。", "flexible, versatile", "inflexible, rigid"],
    ["adapted", "這本手冊已為新使用者改編。", "modified, adjusted", "original, unchanged"],
    ["add up to", "這些費用總計比我們預期的更多。", "total, amount to", "subtract from, fall short of"],
    ["added benefits", "遠端工作為通勤者提供額外好處。", "extra advantages, additional perks", "drawbacks, disadvantages"],
    ["addition", "增加週末營業時間提升了銷售。", "increase, inclusion", "removal, subtraction"],
    ["additional", "如果你需要額外資訊，請聯絡我們。", "extra, further", "less, fewer"],
    ["additional charge", "快遞配送需要支付額外費用。", "extra fee, surcharge", "discount, free service"],
    ["additional fee", "客人必須支付停車的額外費用。", "extra charge, surcharge", "waiver, discount"],
    ["additionally", "此外，這個套裝還包含免費安裝。", "furthermore, in addition", "however, instead"],
    ["address", "經理今天會處理這項客訴。", "handle, deal with", "ignore, avoid"],
    ["address the audience", "執行長會在午餐後向聽眾演說。", "speak to the audience, give a speech", "remain silent, avoid speaking"],
    ["adept", "她很擅長處理難應付的顧客。", "skilled, proficient", "inept, unskilled"],
    ["adequate", "這個房間有足夠的照明可供簡報使用。", "sufficient, enough", "inadequate, insufficient"],
    ["adequately", "這筆預算足以支付差旅費。", "sufficiently, properly", "inadequately, poorly"],
    ["adhere", "所有供應商都必須遵守安全規則。", "follow, comply with", "violate, ignore"],
    ["adjacent", "影印室在接待區旁邊。", "next to, neighboring", "distant, separate"],
    ["adjourn", "主席決定休會。", "close, suspend", "convene, continue"],
    ["adjournment", "董事會宣布休會至星期一。", "suspension, postponement", "continuation, opening"],
    ["adjust", "請在示範前調整螢幕亮度。", "modify, adapt", "leave unchanged, disturb"],
    ["sought after", "有經驗的資料分析師受到許多公司的歡迎。", "in demand, desired", "unwanted, unpopular"],
    ["extravagant", "公司避免為活動做奢侈的裝飾。", "lavish, excessive", "frugal, modest"],
    ["go to extravagant lengths to do", "團隊不遺餘力地想讓客戶留下深刻印象。", "make every effort, go all out", "make little effort, do the minimum"],
    ["collectively", "各部門共同節省了數千美元。", "together, jointly", "individually, separately"],
    ["substantially", "這項折扣大幅降低了總成本。", "considerably, significantly", "slightly, minimally"],
    ["expressively", "她在產品簡報中富有表情地說明。", "vividly, emotionally", "flatly, expressionlessly"],
    ["be expected to do", "所有訪客都應該在接待處簽到。", "be supposed to, be required to", "be unlikely to, be excused from"],
    ["imaginative", "這次活動運用富有想像力的點子吸引顧客。", "creative, inventive", "unimaginative, dull"],
    ["configuration", "技術人員更改了印表機的設定。", "setup, arrangement", "disorganization, disorder"],
    ["place an order", "你可以透過我們的網站下訂單。", "order, make a purchase", "cancel an order, withdraw an order"],
    ["executive", "主管批准了徵才計畫。", "manager, administrator", "subordinate, employee"],
    ["distinguish myself", "我希望透過可靠的工作讓自己脫穎而出。", "stand out, set myself apart", "blend in, go unnoticed"],
    ["covet", "許多設計師都渴望得到年度創新獎。", "desire, crave", "dislike, reject"],
    ["lost and found office", "我把雨傘留在失物招領處。", "lost property office, property desk", "claim desk, personal storage"],
    ["miserly", "小氣的預算限制了團隊的選擇。", "stingy, cheap", "generous, lavish"],
    ["rallying point", "新的使命宣言成為員工的凝聚點。", "focus, gathering point", "dividing issue, source of conflict"],
    ["warden", "管理員在演習後檢查建築物。", "supervisor, custodian", "inmate, visitor"],
    ["as a result of", "由於這次促銷，銷售增加了。", "because of, due to", "despite, regardless of"],
    ["merger", "這次合併創造了一家更大的區域銀行。", "combination, consolidation", "separation, split"],
    ["prospective", "潛在客戶收到了一本詳細手冊。", "potential, likely", "former, current"],
    ["take advantage of", "會員應該利用免費工作坊。", "use, make use of", "miss, ignore"],
    ["promotion", "這次促銷吸引了許多新顧客。", "advertising, advancement", "demotion, suppression"],
    ["emerge from", "幾個想法從規劃會議中產生。", "come from, arise from", "disappear into, vanish from"],
    ["conscientiousness", "她的認真負責讓她成為值得信賴的助理。", "diligence, carefulness", "carelessness, negligence"],
    ["managing director", "總經理下週會拜訪分公司。", "chief executive, general manager", "junior staff, assistant"],
    ["certainly unacceptable", "依合約規定，延遲付款當然無法接受。", "clearly improper, definitely not acceptable", "fully acceptable, perfectly fine"],
    ["employment section", "她在徵才欄找到這則職缺公告。", "job section, recruitment column", "classified sales section, nonjob section"],
    ["a clear description of", "這本手冊清楚描述了流程。", "a precise explanation of, a clear account of", "a vague description of, unclear wording"],
    ["result in", "延誤可能導致額外成本。", "cause, lead to", "prevent, avoid"],
    ["misleading", "沒有適當標籤的圖表具有誤導性。", "deceptive, confusing", "accurate, clear"],
    ["want ad", "他回覆了一則徵求銷售助理的招聘廣告。", "job advertisement, help-wanted ad", "resume, application"],
    ["offence/offense against", "這句話被視為違反公司政策。", "violation of, breach of", "compliance with, respect for"],
    ["hardship", "這項基金支援面臨財務困難的工人。", "difficulty, adversity", "comfort, ease"],
    ["community", "公司捐贈電腦給當地社區。", "local group, society", "individual, isolation"],
    ["census", "人口普查提供有用的人口資料。", "population count, survey", "estimate, guess"],
    ["tick off", "請在檢查後勾選每一項。", "check off, mark", "leave unchecked, ignore"],
    ["grant", "委員會下週將准予核准。", "give, approve", "deny, refuse"],
    ["toll-free", "顧客可以撥打免付費電話取得支援。", "free of charge, no-cost", "paid, chargeable"],
    ["amid", "這家店在激烈競爭中仍持續營業。", "among, during", "outside, away from"],
    ["honor", "學校會在典禮上表揚志工。", "recognize, celebrate", "dishonor, criticize"],
    ["prestigious", "她接受了一家有聲望律師事務所的職位。", "respected, renowned", "unknown, low-status"],
    ["advocates", "這份報告主張更強的隱私保護。", "supports, recommends", "opposes, rejects"],
    ["advocate", "他是更安全工作條件的倡導者。", "supporter, proponent", "opponent, critic"],
    ["unprivileged", "這個慈善機構支持弱勢學生。", "disadvantaged, underprivileged", "privileged, advantaged"],
    ["extravaganza", "年度大型促銷活動星期五開始。", "spectacle, big event", "small event, modest show"],
    ["antique", "這家店販售來自歐洲的古董家具。", "old, vintage", "modern, new"],
    ["anymore", "那台舊印表機已經不再使用了。", "nowadays, any longer", "still, as before"],
    ["apologize", "經理打電話為延誤道歉。", "say sorry, express regret", "blame, defend"],
    ["apparatus", "實驗室器材使用後必須清潔。", "equipment, device", "software, tool-free setup"],
    ["apparel", "這家公司為跑者設計運動服裝。", "clothing, garments", "equipment, hardware"],
    ["apparently", "看來會議已改到星期五。", "seemingly, evidently", "clearly not, secretly"],
    ["appeal", "這項新產品對年輕顧客很有吸引力。", "attraction, request", "repel, discourage"],
    ["appealing", "這本手冊使用吸引人的度假村照片。", "attractive, inviting", "unappealing, unattractive"],
    ["appear", "結果會立刻出現在螢幕上。", "show up, emerge", "disappear, vanish"],
    ["appearance", "整修後大廳的外觀改善了。", "look, arrival", "disappearance, absence"],
    ["appetizer", "客人可以在主菜前選一道開胃菜。", "starter, first course", "dessert, main course"],
    ["applaud", "員工讚賞公司的新訓練政策。", "praise, clap", "criticize, condemn"],
    ["appliance", "這家店為每項家電提供保固。", "device, household machine", "furniture, manual tool"],
    ["applicant", "每位申請人都必須在星期一前提交履歷。", "candidate, requester", "employer, recruiter"],
    ["application", "你的申請本週會被審查。", "request, use", "withdrawal, rejection"],
    ["application form", "請在線上完成申請表。", "request form, registration form", "approval notice, rejection letter"],
    ["apply", "你可以在我們的網站申請這個職位。", "submit, use", "withdraw, ignore"],
    ["apply for", "幾位實習生計畫申請全職工作。", "request, seek", "withdraw from, decline"],
    ["appoint", "董事會下個月會任命一位新主任。", "name, assign", "dismiss, remove"],
    ["appointment", "我和業務經理約了一個會面。", "meeting, reservation", "cancellation, dismissal"],
  ];

  const normalize = (word) =>
    String(word || "")
      .trim()
      .toLowerCase()
      .replace(/\s+/g, " ");

  const normalizeSynonyms = (value) =>
    String(value || "")
      .trim()
      .replace(/\s*[,，]\s*/g, " / ")
      .replace(/\s*\/\s*/g, " / ")
      .replace(/\s{2,}/g, " ");

  return Object.fromEntries(
    entries.map(([word, exampleMeaning, synonyms]) => [
      normalize(word),
      { exampleMeaning, synonyms: normalizeSynonyms(synonyms) },
    ]),
  );
})();
