window.VOCAB_EXTRA_ENRICHMENTS = (() => {
  const entries = [
    ["A as well as B", "along with, together with"],
    ["A be followed by B", "come after, be succeeded by"],
    ["A and B alike", "both A and B, A together with B"],
    ["a complete line of", "a full range of, a whole set of"],
    ["a copy of", "a duplicate of, a reproduction of"],
    ["a couple of", "a few, two or three"],
    ["a glass of", "one cup of, one serving of"],
    ["a great deal", "a lot, considerably"],
    ["a great deal of", "a large amount of, plenty of"],
    ["a large attendance", "a big turnout, a high attendance"],
    ["a letter of gratitude", "thank-you letter, appreciation letter"],
    ["a loaf of", "one loaf, a whole bread"],
    ["a number of", "several, many"],
    ["a piece of equipment", "a device, a machine"],
    ["a range of", "a variety of, an array of"],
    ["a selection of", "a choice of, an assortment of"],
    ["a series of", "a sequence of, a succession of"],
    ["a sheet of", "one page of, one piece of"],
    ["a string of", "a series of, a chain of"],
    ["a variety of", "various, many kinds of"],
    ["various", "different, diverse"],
    ["abandon", "give up, desert"],
    ["abate", "lessen, subside"],
    ["abbreviate", "shorten, condense"],
    ["ability", "skill, capability"],
    ["aboard", "on board, on"],
    ["abolish", "eliminate, cancel"],
    ["abridgment", "summary, shortened version"],
    ["abruptly", "suddenly, unexpectedly"],
    ["absence", "nonattendance, lack"],
    ["absolute", "complete, definite"],
    ["absolutely", "completely, definitely"],
    ["absorbing", "engaging, fascinating"],
    ["abstract", "summary, conceptual"],
    ["abundant", "plentiful, ample"],
    ["abundantly", "plentifully, clearly"],
    ["abuse", "misuse, mistreat"],
    ["accelerate", "speed up, hasten"],
    ["accept", "receive, approve"],
    ["accept an award", "receive a prize, take an award"],
    ["accept the offer", "agree to the offer, take the offer"],
    ["acceptable", "satisfactory, allowable"],
    ["access", "enter, use"],
    ["access road", "entry road, service road"],
    ["access to", "use of, entry to"],
    ["accessibility", "availability, ease of access"],
    ["accessible", "available, reachable"],
    ["accidentally", "by chance, unintentionally"],
    ["acclaim", "praise, approval"],
    ["accommodate", "hold, house"],
    ["accommodation", "lodging, housing"],
    ["accompany", "escort, go with"],
    ["accomplish", "complete, achieve"],
    ["accomplished", "skilled, talented"],
    ["accomplishment", "achievement, success"],
    ["accordance", "compliance, conformity"],
    ["accordingly", "therefore, consequently"],
    ["according to", "based on, as stated by"],
    ["account", "record, account profile"],
    ["account payable", "payable account, debt owed"],
    ["accountable", "responsible, answerable"],
    ["accountant", "bookkeeper, auditor"],
    ["accounting", "bookkeeping, financial reporting"],
    ["accredit", "certify, authorize"],
    ["accrue", "accumulate, build up"],
    ["accumulate", "collect, gather"],
    ["accuracy", "precision, correctness"],
    ["accurate", "correct, precise"],
    ["accurately", "precisely, correctly"],
    ["accuse", "charge, blame"],
    ["accumulation", "buildup, collection"],
    ["accustomed", "used to, familiar with"],
    ["achievable", "attainable, reachable"],
    ["achieve", "attain, accomplish"],
    ["achieve one's goal", "reach one's goal, accomplish one's aim"],
    ["achievement", "accomplishment, success"],
    ["achiever", "high performer, successful person"],
    ["acknowledge", "confirm, admit"],
    ["acquaint", "familiarize, inform"],
    ["acquaintance", "contact, familiar person"],
    ["acquire", "obtain, purchase"],
    ["acquired", "obtained, learned"],
    ["acquisition", "purchase, takeover"],
    ["across from", "opposite, facing"],
    ["across the street", "on the other side of the street, opposite"],
    ["act", "do, take action"],
    ["acting", "temporary, interim"],
    ["activate", "turn on, enable"],
    ["active", "energetic, involved"],
    ["actually", "in fact, really"],
    ["acute", "severe, intense"],
    ["adapt", "adjust, modify"],
    ["adaptability", "flexibility, adjustability"],
    ["adaptable", "flexible, versatile"],
    ["adapted", "modified, adjusted"],
    ["add up to", "total, amount to"],
    ["added benefits", "extra advantages, additional perks"],
    ["addition", "increase, inclusion"],
    ["additional", "extra, further"],
    ["additional charge", "extra fee, surcharge"],
    ["additional fee", "extra charge, surcharge"],
    ["additionally", "furthermore, in addition"],
    ["address", "handle, deal with"],
    ["address the audience", "speak to the audience, give a speech"],
    ["adept", "skilled, proficient"],
    ["adequate", "sufficient, enough"],
    ["adequately", "sufficiently, properly"],
    ["adhere", "follow, comply with"],
    ["adjacent", "next to, neighboring"],
    ["adjourn", "close, suspend"],
    ["adjournment", "suspension, postponement"],
    ["adjust", "modify, adapt"],
    ["sought after", "in demand, desired"],
    ["extravagant", "lavish, excessive"],
    ["go to extravagant lengths to do", "make every effort, go all out"],
    ["collectively", "together, jointly"],
    ["substantially", "considerably, significantly"],
    ["expressively", "vividly, emotionally"],
    ["be expected to do", "be supposed to, be required to"],
    ["imaginative", "creative, inventive"],
    ["configuration", "setup, arrangement"],
    ["place an order", "order, make a purchase"],
    ["executive", "manager, administrator"],
    ["distinguish myself", "stand out, set myself apart"],
    ["covet", "desire, crave"],
    ["lost and found office", "lost property office, property desk"],
    ["miserly", "stingy, cheap"],
    ["rallying point", "focus, gathering point"],
    ["warden", "supervisor, custodian"],
    ["as a result of", "because of, due to"],
    ["merger", "combination, consolidation"],
    ["prospective", "potential, likely"],
    ["take advantage of", "use, make use of"],
    ["promotion", "advertising, advancement"],
    ["emerge from", "come from, arise from"],
    ["conscientiousness", "diligence, carefulness"],
    ["managing director", "chief executive, general manager"],
    ["certainly unacceptable", "clearly improper, definitely not acceptable"],
    ["employment section", "job section, recruitment column"],
    ["a clear description of", "a precise explanation of, a clear account of"],
    ["result in", "cause, lead to"],
    ["misleading", "deceptive, confusing"],
    ["want ad", "job advertisement, help-wanted ad"],
    ["offence/offense against", "violation of, breach of"],
    ["hardship", "difficulty, adversity"],
    ["community", "local group, society"],
    ["census", "population count, survey"],
    ["tick off", "check off, mark"],
    ["grant", "give, approve"],
    ["toll-free", "free of charge, no-cost"],
    ["amid", "among, during"],
    ["honor", "recognize, celebrate"],
    ["prestigious", "respected, renowned"],
    ["advocates", "supports, recommends"],
    ["advocate", "supporter, proponent"],
    ["unprivileged", "disadvantaged, underprivileged"],
    ["extravaganza", "spectacle, big event"],
    ["antique", "old, vintage"],
    ["anymore", "nowadays, any longer"],
    ["apologize", "say sorry, express regret"],
    ["apparatus", "equipment, device"],
    ["apparel", "clothing, garments"],
    ["apparently", "seemingly, evidently"],
    ["appeal", "attraction, request"],
    ["appealing", "attractive, inviting"],
    ["appear", "show up, emerge"],
    ["appearance", "look, arrival"],
    ["appetizer", "starter, first course"],
    ["applaud", "praise, clap"],
    ["appliance", "device, household machine"],
    ["applicant", "candidate, requester"],
    ["application", "request, use"],
    ["application form", "request form, registration form"],
    ["apply", "submit, use"],
    ["apply for", "request, seek"],
    ["appoint", "name, assign"],
    ["appointment", "meeting, reservation"],
  ];

  const normalize = (word) =>
    String(word || "")
      .trim()
      .toLowerCase()
      .replace(/\s+/g, " ");

  const normalizeSynonyms = (value) =>
    String(value || "")
      .trim()
      .replace(/\s*[,，]\s*/g, " / ")
      .replace(/\s*\/\s*/g, " / ")
      .replace(/\s{2,}/g, " ");

  return Object.fromEntries(
    entries.map(([word, synonyms]) => [
      normalize(word),
      { synonyms: normalizeSynonyms(synonyms) },
    ]),
  );
})();
