window.PDF_VOCAB_CARDS = [
  { id: "pdf-a-001", word: "A as well as B", meaning: "A 和 B；不但 B 而且 A", tag: "A 開頭 PDF" },
  { id: "pdf-a-002", word: "A be followed by B", meaning: "A 後面接 B", tag: "A 開頭 PDF" },
  { id: "pdf-a-003", word: "A and B alike", meaning: "A 和 B 都一樣", tag: "A 開頭 PDF" },
  { id: "pdf-a-004", word: "a complete line of", meaning: "一整套；完整系列的", tag: "A 開頭 PDF" },
  { id: "pdf-a-005", word: "a copy of", meaning: "一份；一本；一張", tag: "A 開頭 PDF" },
  { id: "pdf-a-006", word: "a couple of", meaning: "幾個；兩個", tag: "A 開頭 PDF" },
  { id: "pdf-a-007", word: "a glass of", meaning: "一杯", tag: "A 開頭 PDF" },
  { id: "pdf-a-008", word: "a great deal", meaning: "許多；大量", tag: "A 開頭 PDF" },
  { id: "pdf-a-009", word: "a great deal of", meaning: "許多；大量的", tag: "A 開頭 PDF" },
  { id: "pdf-a-010", word: "a large attendance", meaning: "大量出席人數", tag: "A 開頭 PDF" },
  { id: "pdf-a-011", word: "a letter of gratitude", meaning: "感謝信", tag: "A 開頭 PDF" },
  { id: "pdf-a-012", word: "a loaf of", meaning: "一條；一塊，常指麵包", tag: "A 開頭 PDF" },
  { id: "pdf-a-013", word: "a number of", meaning: "許多；若干", tag: "A 開頭 PDF" },
  { id: "pdf-a-014", word: "a piece of equipment", meaning: "一件設備", tag: "A 開頭 PDF" },
  { id: "pdf-a-015", word: "a range of", meaning: "一系列；範圍", tag: "A 開頭 PDF" },
  { id: "pdf-a-016", word: "a selection of", meaning: "精選；一組", tag: "A 開頭 PDF" },
  { id: "pdf-a-017", word: "a series of", meaning: "一連串；一系列", tag: "A 開頭 PDF" },
  { id: "pdf-a-018", word: "a sheet of", meaning: "一張", tag: "A 開頭 PDF" },
  { id: "pdf-a-019", word: "a string of", meaning: "一串；一連串", tag: "A 開頭 PDF" },
  { id: "pdf-a-020", word: "a variety of", meaning: "各種各樣的", tag: "A 開頭 PDF" },
  { id: "pdf-a-021", word: "various", meaning: "各種的", tag: "A 開頭 PDF" },
  { id: "pdf-a-022", word: "abandon", meaning: "放棄；拋棄", tag: "A 開頭 PDF" },
  { id: "pdf-a-023", word: "abate", meaning: "減少；減弱", tag: "A 開頭 PDF" },
  { id: "pdf-a-024", word: "abbreviate", meaning: "縮寫；縮短", tag: "A 開頭 PDF" },
  { id: "pdf-a-025", word: "ability", meaning: "能力", tag: "A 開頭 PDF" },
  { id: "pdf-a-026", word: "aboard", meaning: "在船／飛機／車上；上船／登機", tag: "A 開頭 PDF" },
  { id: "pdf-a-027", word: "abolish", meaning: "廢除", tag: "A 開頭 PDF" },
  { id: "pdf-a-028", word: "abridgment", meaning: "刪節本；縮寫", tag: "A 開頭 PDF" },
  { id: "pdf-a-029", word: "abruptly", meaning: "突然地；唐突地", tag: "A 開頭 PDF" },
  { id: "pdf-a-030", word: "absence", meaning: "缺席；缺乏", tag: "A 開頭 PDF" },
  { id: "pdf-a-031", word: "absolute", meaning: "絕對的；完全的", tag: "A 開頭 PDF" },
  { id: "pdf-a-032", word: "absolutely", meaning: "絕對地；完全地", tag: "A 開頭 PDF" },
  { id: "pdf-a-033", word: "absorbing", meaning: "引人入勝的；吸引人的", tag: "A 開頭 PDF" },
  { id: "pdf-a-034", word: "abstract", meaning: "抽象的；摘要", tag: "A 開頭 PDF" },
  { id: "pdf-a-035", word: "abundant", meaning: "豐富的；充足的", tag: "A 開頭 PDF" },
  { id: "pdf-a-036", word: "abundantly", meaning: "豐富地；大量地", tag: "A 開頭 PDF" },
  { id: "pdf-a-037", word: "abuse", meaning: "濫用；虐待", tag: "A 開頭 PDF" },
  { id: "pdf-a-038", word: "accelerate", meaning: "加速", tag: "A 開頭 PDF" },
  { id: "pdf-a-039", word: "accept", meaning: "接受", tag: "A 開頭 PDF" },
  { id: "pdf-a-040", word: "accept an award", meaning: "接受獎項", tag: "A 開頭 PDF" },
  { id: "pdf-a-041", word: "accept the offer", meaning: "接受提議／錄取／報價", tag: "A 開頭 PDF" },
  { id: "pdf-a-042", word: "acceptable", meaning: "可接受的", tag: "A 開頭 PDF" },
  { id: "pdf-a-043", word: "access", meaning: "進入；取得；使用權", tag: "A 開頭 PDF" },
  { id: "pdf-a-044", word: "access road", meaning: "進出道路；通道", tag: "A 開頭 PDF" },
  { id: "pdf-a-045", word: "access to", meaning: "取得／使用……的機會", tag: "A 開頭 PDF" },
  { id: "pdf-a-046", word: "accessibility", meaning: "可接近性；便利性", tag: "A 開頭 PDF" },
  { id: "pdf-a-047", word: "accessible", meaning: "可進入的；可取得的", tag: "A 開頭 PDF" },
  { id: "pdf-a-048", word: "accidentally", meaning: "意外地；偶然地", tag: "A 開頭 PDF" },
  { id: "pdf-a-049", word: "acclaim", meaning: "稱讚；讚譽", tag: "A 開頭 PDF" },
  { id: "pdf-a-050", word: "accommodate", meaning: "容納；提供住宿；配合", tag: "A 開頭 PDF" },
  { id: "pdf-a-051", word: "accommodation", meaning: "住宿；膳宿；調整", tag: "A 開頭 PDF" },
  { id: "pdf-a-052", word: "accompany", meaning: "陪伴；伴隨", tag: "A 開頭 PDF" },
  { id: "pdf-a-053", word: "accomplish", meaning: "完成；達成", tag: "A 開頭 PDF" },
  { id: "pdf-a-054", word: "accomplished", meaning: "有成就的；熟練的", tag: "A 開頭 PDF" },
  { id: "pdf-a-055", word: "accomplishment", meaning: "成就；完成", tag: "A 開頭 PDF" },
  { id: "pdf-a-056", word: "accordance", meaning: "一致；符合", tag: "A 開頭 PDF" },
  { id: "pdf-a-057", word: "accordingly", meaning: "因此；相應地", tag: "A 開頭 PDF" },
  { id: "pdf-a-058", word: "according to", meaning: "根據；依照", tag: "A 開頭 PDF" },
  { id: "pdf-a-059", word: "account", meaning: "帳戶；說明；描述", tag: "A 開頭 PDF" },
  { id: "pdf-a-060", word: "account payable", meaning: "應付帳款", tag: "A 開頭 PDF" },
  { id: "pdf-a-061", word: "accountable", meaning: "應負責的", tag: "A 開頭 PDF" },
  { id: "pdf-a-062", word: "accountant", meaning: "會計師；會計人員", tag: "A 開頭 PDF" },
  { id: "pdf-a-063", word: "accounting", meaning: "會計", tag: "A 開頭 PDF" },
  { id: "pdf-a-064", word: "accredit", meaning: "認可；授權；歸因於", tag: "A 開頭 PDF" },
  { id: "pdf-a-065", word: "accrue", meaning: "累積；產生", tag: "A 開頭 PDF" },
  { id: "pdf-a-066", word: "accumulate", meaning: "累積；積聚", tag: "A 開頭 PDF" },
  { id: "pdf-a-067", word: "accuracy", meaning: "準確性", tag: "A 開頭 PDF" },
  { id: "pdf-a-068", word: "accurate", meaning: "準確的", tag: "A 開頭 PDF" },
  { id: "pdf-a-069", word: "accurately", meaning: "準確地", tag: "A 開頭 PDF" },
  { id: "pdf-a-070", word: "accuse", meaning: "指控；控告", tag: "A 開頭 PDF" },
  { id: "pdf-a-071", word: "accumulation", meaning: "累積；堆積", tag: "A 開頭 PDF" },
  { id: "pdf-a-072", word: "accustomed", meaning: "習慣於", tag: "A 開頭 PDF" },
  { id: "pdf-a-073", word: "achievable", meaning: "可達成的", tag: "A 開頭 PDF" },
  { id: "pdf-a-074", word: "achieve", meaning: "達成；實現", tag: "A 開頭 PDF" },
  { id: "pdf-a-075", word: "achieve one's goal", meaning: "達成某人的目標", tag: "A 開頭 PDF" },
  { id: "pdf-a-076", word: "achievement", meaning: "成就；達成", tag: "A 開頭 PDF" },
  { id: "pdf-a-077", word: "achiever", meaning: "成功人士；有成就者", tag: "A 開頭 PDF" },
  { id: "pdf-a-078", word: "acknowledge", meaning: "承認；告知收到；致謝", tag: "A 開頭 PDF" },
  { id: "pdf-a-079", word: "acquaint", meaning: "使熟悉；使了解", tag: "A 開頭 PDF" },
  { id: "pdf-a-080", word: "acquaintance", meaning: "熟人；認識", tag: "A 開頭 PDF" },
  { id: "pdf-a-081", word: "acquire", meaning: "獲得；取得", tag: "A 開頭 PDF" },
  { id: "pdf-a-082", word: "acquired", meaning: "後天取得的；已獲得的", tag: "A 開頭 PDF" },
  { id: "pdf-a-083", word: "acquisition", meaning: "取得；收購；獲得物", tag: "A 開頭 PDF" },
  { id: "pdf-a-084", word: "across from", meaning: "在……對面", tag: "A 開頭 PDF" },
  { id: "pdf-a-085", word: "across the street", meaning: "在街道對面", tag: "A 開頭 PDF" },
  { id: "pdf-a-086", word: "act", meaning: "行動；行為；法案；表演", tag: "A 開頭 PDF" },
  { id: "pdf-a-087", word: "acting", meaning: "表演；臨時代理的", tag: "A 開頭 PDF" },
  { id: "pdf-a-088", word: "activate", meaning: "啟動；激活", tag: "A 開頭 PDF" },
  { id: "pdf-a-089", word: "active", meaning: "活躍的；主動的", tag: "A 開頭 PDF" },
  { id: "pdf-a-090", word: "actually", meaning: "其實；實際上", tag: "A 開頭 PDF" },
  { id: "pdf-a-091", word: "acute", meaning: "嚴重的；敏銳的；急性的", tag: "A 開頭 PDF" },
  { id: "pdf-a-092", word: "adapt", meaning: "適應；改編", tag: "A 開頭 PDF" },
  { id: "pdf-a-093", word: "adaptability", meaning: "適應能力", tag: "A 開頭 PDF" },
  { id: "pdf-a-094", word: "adaptable", meaning: "能適應的", tag: "A 開頭 PDF" },
  { id: "pdf-a-095", word: "adapted", meaning: "改編的；適應的", tag: "A 開頭 PDF" },
  { id: "pdf-a-096", word: "add up to", meaning: "總計為；意味著", tag: "A 開頭 PDF" },
  { id: "pdf-a-097", word: "added benefits", meaning: "額外好處", tag: "A 開頭 PDF" },
  { id: "pdf-a-098", word: "addition", meaning: "增加；加法", tag: "A 開頭 PDF" },
  { id: "pdf-a-099", word: "additional", meaning: "額外的；附加的", tag: "A 開頭 PDF" },
  { id: "pdf-a-100", word: "additional charge", meaning: "額外費用", tag: "A 開頭 PDF" },
  { id: "pdf-a-101", word: "additional fee", meaning: "額外費用", tag: "A 開頭 PDF" },
  { id: "pdf-a-102", word: "additionally", meaning: "此外；另外", tag: "A 開頭 PDF" },
  { id: "pdf-a-103", word: "address", meaning: "地址；演說；處理", tag: "A 開頭 PDF" },
  { id: "pdf-a-104", word: "address the audience", meaning: "向觀眾／聽眾演說", tag: "A 開頭 PDF" },
  { id: "pdf-a-105", word: "adept", meaning: "熟練的；擅長的", tag: "A 開頭 PDF" },
  { id: "pdf-a-106", word: "adequate", meaning: "足夠的；適當的", tag: "A 開頭 PDF" },
  { id: "pdf-a-107", word: "adequately", meaning: "充分地；適當地", tag: "A 開頭 PDF" },
  { id: "pdf-a-108", word: "adhere", meaning: "遵守；黏附；堅持", tag: "A 開頭 PDF" },
  { id: "pdf-a-109", word: "adjacent", meaning: "鄰近的；相鄰的", tag: "A 開頭 PDF" },
  { id: "pdf-a-110", word: "adjourn", meaning: "休會；延期", tag: "A 開頭 PDF" },
  { id: "pdf-a-111", word: "adjournment", meaning: "休會；延期", tag: "A 開頭 PDF" },
  { id: "pdf-a-112", word: "adjust", meaning: "調整；適應", tag: "A 開頭 PDF" },
  { id: "pdf-notes-001", word: "sought after", meaning: "很吃香的；受歡迎的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-002", word: "extravagant", meaning: "浪費的；奢侈的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-003", word: "go to extravagant lengths to do", meaning: "不遺餘力地做某事", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-004", word: "collectively", meaning: "集體地；共同地（adv.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-005", word: "substantially", meaning: "實質地；相當地；大幅地（adv.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-006", word: "expressively", meaning: "富表現力地（adv.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-007", word: "be expected to do", meaning: "被預期做；應該會做", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-008", word: "imaginative", meaning: "富想像力的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-009", word: "configuration", meaning: "配置；結構（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-010", word: "place an order", meaning: "下訂單", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-011", word: "executive", meaning: "主管；行政人員（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-012", word: "distinguish myself", meaning: "使自己脫穎而出", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-013", word: "covet", meaning: "渴望得到；覬覦（v.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-014", word: "lost and found office", meaning: "失物招領處", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-015", word: "miserly", meaning: "吝嗇的；小氣的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-016", word: "rallying point", meaning: "凝聚點；號召中心（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-017", word: "warden", meaning: "管理員；監獄長（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-018", word: "as a result of", meaning: "由於；因為", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-019", word: "merger", meaning: "合併（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-020", word: "prospective", meaning: "未來的；潛在的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-021", word: "take advantage of", meaning: "利用", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-022", word: "promotion", meaning: "升遷；促銷；推廣（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-023", word: "emerge from", meaning: "源自；從……出現", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-024", word: "conscientiousness", meaning: "盡責；認真負責（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-025", word: "managing director", meaning: "總經理；常務董事（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-026", word: "certainly unacceptable", meaning: "當然無法接受", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-027", word: "employment section", meaning: "求職版；徵才欄", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-028", word: "a clear description of", meaning: "對……的清楚描述", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-029", word: "result in", meaning: "導致；造成", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-030", word: "misleading", meaning: "誤導的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-031", word: "want ad", meaning: "徵才廣告；招聘廣告（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-032", word: "offence/offense against", meaning: "違反；冒犯", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-033", word: "hardship", meaning: "困苦；艱難（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-034", word: "community", meaning: "社區；群體（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-035", word: "census", meaning: "人口普查（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-036", word: "tick off", meaning: "勾選；列舉；惹惱（v.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-037", word: "grant", meaning: "授予；准予（v.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-038", word: "toll-free", meaning: "免費的；免付費的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-039", word: "amid", meaning: "在……之中；在……期間", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-040", word: "honor", meaning: "授予榮譽；表揚（v.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-041", word: "prestigious", meaning: "有聲望的；享有盛名的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-042", word: "advocates", meaning: "提倡；主張（v.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-043", word: "advocate", meaning: "倡導者；支持者（n.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-044", word: "unprivileged", meaning: "弱勢的；缺乏特權的（adj.）", tag: "手寫筆記 PDF" },
  { id: "pdf-notes-045", word: "extravaganza", meaning: "盛大活動；豪華表演（n.）", tag: "手寫筆記 PDF" },
];

const VOCAB_CATEGORY_LABELS = {
  A: "A 核心高頻",
  B: "B 商務片語",
  C: "C 修飾描述",
  D: "D 進階專用",
};

const VOCAB_ENRICHMENTS = {
  "pdf-a-001": ["B", "conj. phr.", "The proposal includes a timeline as well as a budget."],
  "pdf-a-002": ["B", "sentence pattern", "The presentation will be followed by a brief question period."],
  "pdf-a-003": ["B", "phr.", "Managers and interns alike attended the workshop."],
  "pdf-a-004": ["B", "n. phr.", "The store offers a complete line of office furniture."],
  "pdf-a-005": ["A", "n. phr.", "Please send a copy of the invoice to accounting."],
  "pdf-a-006": ["A", "quant. phr.", "We need a couple of chairs for the meeting room."],
  "pdf-a-007": ["A", "n. phr.", "She ordered a glass of water before the seminar."],
  "pdf-a-008": ["A", "adv. phr.", "The new policy helped a great deal."],
  "pdf-a-009": ["A", "quant. phr.", "The project requires a great deal of planning."],
  "pdf-a-010": ["B", "n. phr.", "The conference had a large attendance this year."],
  "pdf-a-011": ["B", "n. phr.", "He wrote a letter of gratitude to the volunteers."],
  "pdf-a-012": ["A", "quant. phr.", "She bought a loaf of bread on her way home."],
  "pdf-a-013": ["A", "quant. phr.", "A number of employees asked for training."],
  "pdf-a-014": ["B", "n. phr.", "A technician inspected each piece of equipment."],
  "pdf-a-015": ["B", "n. phr.", "The hotel offers a range of services for guests."],
  "pdf-a-016": ["B", "n. phr.", "The catalog includes a selection of laptops."],
  "pdf-a-017": ["A", "n. phr.", "The manager scheduled a series of interviews."],
  "pdf-a-018": ["A", "quant. phr.", "Please place a sheet of paper on each desk."],
  "pdf-a-019": ["C", "n. phr.", "The team celebrated a string of successful launches."],
  "pdf-a-020": ["A", "quant. phr.", "The buffet provides a variety of healthy options."],
  "pdf-a-021": ["A", "adj.", "Various departments joined the budget meeting."],
  "pdf-a-022": ["A", "v.", "The company did not abandon the expansion plan."],
  "pdf-a-023": ["D", "v.", "The heavy rain began to abate before noon."],
  "pdf-a-024": ["B", "v.", "You can abbreviate the department name on the form."],
  "pdf-a-025": ["A", "n.", "Her ability to solve problems impressed the client."],
  "pdf-a-026": ["A", "prep./adv.", "Passengers must be aboard the train by 8 a.m."],
  "pdf-a-027": ["D", "v.", "The city plans to abolish the outdated fee."],
  "pdf-a-028": ["D", "n.", "The editor prepared an abridgment of the report."],
  "pdf-a-029": ["C", "adv.", "The meeting ended abruptly after the announcement."],
  "pdf-a-030": ["A", "n.", "Please inform HR of any absence in advance."],
  "pdf-a-031": ["C", "adj.", "The deadline is absolute and cannot be changed."],
  "pdf-a-032": ["C", "adv.", "The figures are absolutely correct."],
  "pdf-a-033": ["C", "adj.", "The training video was surprisingly absorbing."],
  "pdf-a-034": ["D", "n./adj.", "The article begins with a short abstract."],
  "pdf-a-035": ["C", "adj.", "The region has abundant natural resources."],
  "pdf-a-036": ["C", "adv.", "The brochure makes the benefits abundantly clear."],
  "pdf-a-037": ["D", "n./v.", "Employees should not abuse company resources."],
  "pdf-a-038": ["A", "v.", "The new software will accelerate order processing."],
  "pdf-a-039": ["A", "v.", "We accept payments by credit card."],
  "pdf-a-040": ["B", "v. phr.", "The designer will accept an award at the ceremony."],
  "pdf-a-041": ["B", "v. phr.", "She decided to accept the offer from the firm."],
  "pdf-a-042": ["C", "adj.", "Your revised schedule is acceptable to the client."],
  "pdf-a-043": ["A", "n./v.", "Only staff members can access the database."],
  "pdf-a-044": ["B", "n. phr.", "Trucks should use the access road behind the warehouse."],
  "pdf-a-045": ["B", "n. phr.", "All members have access to the online library."],
  "pdf-a-046": ["D", "n.", "The renovation improved accessibility at the station."],
  "pdf-a-047": ["C", "adj.", "The files are accessible through the shared drive."],
  "pdf-a-048": ["C", "adv.", "I accidentally deleted the old message."],
  "pdf-a-049": ["D", "n./v.", "The product won acclaim from industry experts."],
  "pdf-a-050": ["A", "v.", "The hotel can accommodate up to 300 guests."],
  "pdf-a-051": ["B", "n.", "The company arranged accommodation for visiting staff."],
  "pdf-a-052": ["A", "v.", "A guide will accompany the guests during the tour."],
  "pdf-a-053": ["A", "v.", "We can accomplish the task by Friday."],
  "pdf-a-054": ["C", "adj.", "She is an accomplished public speaker."],
  "pdf-a-055": ["A", "n.", "Finishing the project was a major accomplishment."],
  "pdf-a-056": ["B", "n.", "All refunds are processed in accordance with company policy."],
  "pdf-a-057": ["C", "adv.", "Demand increased, and prices rose accordingly."],
  "pdf-a-058": ["B", "prep. phr.", "According to the report, sales improved in April."],
  "pdf-a-059": ["B", "n./v.", "Please update your account information."],
  "pdf-a-060": ["B", "n. phr.", "The accountant checked each account payable before payment."],
  "pdf-a-061": ["C", "adj.", "Team leaders are accountable for final results."],
  "pdf-a-062": ["B", "n.", "The accountant prepared the quarterly report."],
  "pdf-a-063": ["B", "n.", "She works in the accounting department."],
  "pdf-a-064": ["D", "v.", "The agency will accredit the training program."],
  "pdf-a-065": ["D", "v.", "Interest will accrue from the date of purchase."],
  "pdf-a-066": ["D", "v.", "Receipts can accumulate quickly during travel."],
  "pdf-a-067": ["A", "n.", "Please check the accuracy of the figures."],
  "pdf-a-068": ["A", "adj.", "The survey results were accurate."],
  "pdf-a-069": ["C", "adv.", "The system records attendance accurately."],
  "pdf-a-070": ["D", "v.", "The customer did not accuse anyone directly."],
  "pdf-a-071": ["D", "n.", "The accumulation of emails slowed the response time."],
  "pdf-a-072": ["C", "adj.", "New employees soon become accustomed to the schedule."],
  "pdf-a-073": ["C", "adj.", "The sales target is challenging but achievable."],
  "pdf-a-074": ["A", "v.", "The team hopes to achieve record sales this quarter."],
  "pdf-a-075": ["B", "v. phr.", "Regular practice helped her achieve her goal."],
  "pdf-a-076": ["A", "n.", "The award recognized his achievement in marketing."],
  "pdf-a-077": ["D", "n.", "The scholarship is designed for high achievers."],
  "pdf-a-078": ["A", "v.", "Please acknowledge receipt of this email."],
  "pdf-a-079": ["D", "v.", "The orientation will acquaint interns with office rules."],
  "pdf-a-080": ["D", "n.", "I met an old acquaintance at the trade show."],
  "pdf-a-081": ["A", "v.", "The firm plans to acquire a smaller competitor."],
  "pdf-a-082": ["C", "adj.", "His acquired skills helped him change careers."],
  "pdf-a-083": ["B", "n.", "The acquisition expanded the company's product line."],
  "pdf-a-084": ["A", "prep. phr.", "The bank is across from the post office."],
  "pdf-a-085": ["A", "prep. phr.", "A new cafe opened across the street."],
  "pdf-a-086": ["A", "n./v.", "The supervisor must act quickly in an emergency."],
  "pdf-a-087": ["C", "adj./n.", "The acting director approved the request."],
  "pdf-a-088": ["A", "v.", "Use this code to activate your account."],
  "pdf-a-089": ["A", "adj.", "She remains active in local business groups."],
  "pdf-a-090": ["A", "adv.", "The repair actually took less than an hour."],
  "pdf-a-091": ["D", "adj.", "The factory faces an acute shortage of workers."],
  "pdf-a-092": ["A", "v.", "The team must adapt to the new system."],
  "pdf-a-093": ["C", "n.", "Adaptability is valuable in a changing workplace."],
  "pdf-a-094": ["C", "adj.", "The software is adaptable to different industries."],
  "pdf-a-095": ["C", "adj.", "The manual was adapted for new users."],
  "pdf-a-096": ["B", "phr. v.", "The fees add up to more than we expected."],
  "pdf-a-097": ["B", "n. phr.", "Remote work offers added benefits for commuters."],
  "pdf-a-098": ["A", "n.", "The addition of weekend hours increased sales."],
  "pdf-a-099": ["A", "adj.", "Please contact us if you need additional information."],
  "pdf-a-100": ["B", "n. phr.", "There is an additional charge for express delivery."],
  "pdf-a-101": ["B", "n. phr.", "Guests must pay an additional fee for parking."],
  "pdf-a-102": ["C", "adv.", "Additionally, the package includes free installation."],
  "pdf-a-103": ["A", "n./v.", "The manager will address the complaint today."],
  "pdf-a-104": ["B", "v. phr.", "The CEO will address the audience after lunch."],
  "pdf-a-105": ["C", "adj.", "She is adept at handling difficult customers."],
  "pdf-a-106": ["C", "adj.", "The room has adequate lighting for the presentation."],
  "pdf-a-107": ["C", "adv.", "The budget adequately covers travel expenses."],
  "pdf-a-108": ["D", "v.", "All vendors must adhere to safety rules."],
  "pdf-a-109": ["C", "adj.", "The copy room is adjacent to the reception area."],
  "pdf-a-110": ["B", "v.", "The chairperson decided to adjourn the meeting."],
  "pdf-a-111": ["B", "n.", "The board announced an adjournment until Monday."],
  "pdf-a-112": ["A", "v.", "Please adjust the screen brightness before the demo."],
  "pdf-notes-001": ["C", "adj.", "Experienced data analysts are sought after by many firms."],
  "pdf-notes-002": ["C", "adj.", "The company avoided extravagant decorations for the event."],
  "pdf-notes-003": ["D", "v. phr.", "The team went to extravagant lengths to impress the client."],
  "pdf-notes-004": ["C", "adv.", "The departments collectively saved thousands of dollars."],
  "pdf-notes-005": ["C", "adv.", "The discount substantially reduced the total cost."],
  "pdf-notes-006": ["C", "adv.", "She spoke expressively during the product presentation."],
  "pdf-notes-007": ["B", "v. phr.", "All visitors are expected to sign in at reception."],
  "pdf-notes-008": ["C", "adj.", "The campaign used imaginative ideas to attract customers."],
  "pdf-notes-009": ["D", "n.", "The technician changed the configuration of the printer."],
  "pdf-notes-010": ["B", "v. phr.", "You can place an order through our website."],
  "pdf-notes-011": ["B", "n./adj.", "The executive approved the hiring plan."],
  "pdf-notes-012": ["D", "v. phr.", "I hope to distinguish myself through reliable work."],
  "pdf-notes-013": ["D", "v.", "Many designers covet the annual innovation award."],
  "pdf-notes-014": ["B", "n. phr.", "I left my umbrella at the lost and found office."],
  "pdf-notes-015": ["D", "adj.", "A miserly budget limited the team's options."],
  "pdf-notes-016": ["D", "n. phr.", "The new mission statement became a rallying point for employees."],
  "pdf-notes-017": ["D", "n.", "The warden checked the building after the drill."],
  "pdf-notes-018": ["B", "prep. phr.", "Sales increased as a result of the promotion."],
  "pdf-notes-019": ["B", "n.", "The merger created a larger regional bank."],
  "pdf-notes-020": ["C", "adj.", "Prospective clients received a detailed brochure."],
  "pdf-notes-021": ["B", "v. phr.", "Members should take advantage of the free workshop."],
  "pdf-notes-022": ["B", "n.", "The promotion attracted many new customers."],
  "pdf-notes-023": ["D", "phr. v.", "Several ideas emerged from the planning session."],
  "pdf-notes-024": ["D", "n.", "Her conscientiousness made her a trusted assistant."],
  "pdf-notes-025": ["B", "n. phr.", "The managing director will visit the branch next week."],
  "pdf-notes-026": ["C", "adj. phr.", "Late payments are certainly unacceptable under the contract."],
  "pdf-notes-027": ["B", "n. phr.", "She found the job posting in the employment section."],
  "pdf-notes-028": ["B", "n. phr.", "The manual gives a clear description of the process."],
  "pdf-notes-029": ["B", "phr. v.", "Delays may result in extra costs."],
  "pdf-notes-030": ["C", "adj.", "The chart was misleading without proper labels."],
  "pdf-notes-031": ["B", "n. phr.", "He replied to a want ad for a sales assistant."],
  "pdf-notes-032": ["D", "n. phr.", "The remark was treated as an offense against company policy."],
  "pdf-notes-033": ["D", "n.", "The fund supports workers facing financial hardship."],
  "pdf-notes-034": ["A", "n.", "The company donated computers to the local community."],
  "pdf-notes-035": ["D", "n.", "The census provides useful population data."],
  "pdf-notes-036": ["D", "phr. v.", "Please tick off each item after inspection."],
  "pdf-notes-037": ["A", "v./n.", "The committee will grant approval next week."],
  "pdf-notes-038": ["B", "adj.", "Customers can call the toll-free number for support."],
  "pdf-notes-039": ["D", "prep.", "The store stayed open amid heavy competition."],
  "pdf-notes-040": ["A", "v./n.", "The school will honor volunteers at the ceremony."],
  "pdf-notes-041": ["C", "adj.", "She accepted a position at a prestigious law firm."],
  "pdf-notes-042": ["B", "v.", "The report advocates stronger privacy protections."],
  "pdf-notes-043": ["B", "n./v.", "He is an advocate for safer working conditions."],
  "pdf-notes-044": ["D", "adj.", "The charity supports unprivileged students."],
  "pdf-notes-045": ["D", "n.", "The annual sales extravaganza starts on Friday."],
};

window.PDF_VOCAB_CARDS = window.PDF_VOCAB_CARDS.map((card) => {
  const enrichment = VOCAB_ENRICHMENTS[card.id];

  if (!enrichment) {
    return card;
  }

  const [category, partOfSpeech, example] = enrichment;

  return {
    ...card,
    source: card.tag,
    tag: VOCAB_CATEGORY_LABELS[category] || card.tag,
    partOfSpeech,
    example,
  };
});

const READABLE_CATEGORY_LABELS = {
  A: "A 基礎單字",
  B: "B 片語搭配",
  C: "C 形容副詞",
  D: "D 進階單字",
};

window.PDF_VOCAB_CARDS = window.PDF_VOCAB_CARDS.map((card) => {
  const category = VOCAB_ENRICHMENTS[card.id]?.[0];
  return category ? { ...card, tag: READABLE_CATEGORY_LABELS[category] || card.tag } : card;
});

const IMPORTED_JSON_1_CARDS = [
  {
    id: "json-1-001",
    word: "antique",
    meaning: "\u53e4\u8463\uff1b\u53e4\u8001\u7684",
    partOfSpeech: "n./adj.",
    example: "The shop sells antique furniture from Europe.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-002",
    word: "anymore",
    meaning: "\u518d\uff1b\u4e0d\u518d",
    partOfSpeech: "adv.",
    example: "The old printer is not used anymore.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-003",
    word: "apologize",
    meaning: "\u9053\u6b49",
    partOfSpeech: "v.",
    example: "The manager called to apologize for the delay.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-004",
    word: "apparatus",
    meaning: "\u5668\u68b0\uff1b\u8a2d\u5099",
    partOfSpeech: "n.",
    example: "The laboratory apparatus must be cleaned after use.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-005",
    word: "apparel",
    meaning: "\u670d\u88dd",
    partOfSpeech: "n.",
    example: "The company designs athletic apparel for runners.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-006",
    word: "apparently",
    meaning: "\u986f\u7136\u5730\uff1b\u770b\u4f86",
    partOfSpeech: "adv.",
    example: "Apparently, the meeting has been moved to Friday.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-007",
    word: "appeal",
    meaning: "\u547c\u7c72\uff1b\u5438\u5f15\u529b\uff1b\u4e0a\u8a34",
    partOfSpeech: "n./v.",
    example: "The new product has strong appeal among young customers.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-008",
    word: "appealing",
    meaning: "\u5438\u5f15\u4eba\u7684",
    partOfSpeech: "adj.",
    example: "The brochure uses appealing photos of the resort.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-009",
    word: "appear",
    meaning: "\u51fa\u73fe\uff1b\u4f3c\u4e4e",
    partOfSpeech: "v.",
    example: "The results appear on the screen immediately.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-010",
    word: "appearance",
    meaning: "\u5916\u8868\uff1b\u51fa\u73fe",
    partOfSpeech: "n.",
    example: "The lobby's appearance improved after the renovation.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-011",
    word: "appetizer",
    meaning: "\u958b\u80c3\u83dc",
    partOfSpeech: "n.",
    example: "Guests can choose an appetizer before the main course.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-012",
    word: "applaud",
    meaning: "\u9f13\u638c\uff1b\u8b9a\u8cde",
    partOfSpeech: "v.",
    example: "Employees applaud the company's new training policy.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-013",
    word: "appliance",
    meaning: "\u5bb6\u96fb\u7528\u54c1",
    partOfSpeech: "n.",
    example: "The store offers a warranty on every appliance.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-014",
    word: "applicant",
    meaning: "\u7533\u8acb\u4eba",
    partOfSpeech: "n.",
    example: "Each applicant must submit a resume by Monday.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-015",
    word: "application",
    meaning: "\u7533\u8acb\uff1b\u61c9\u7528",
    partOfSpeech: "n.",
    example: "Your application will be reviewed this week.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-016",
    word: "application form",
    meaning: "\u7533\u8acb\u8868",
    partOfSpeech: "n. phr.",
    example: "Please complete the application form online.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-017",
    word: "apply",
    meaning: "\u7533\u8acb\uff1b\u61c9\u7528",
    partOfSpeech: "v.",
    example: "You can apply for the position on our website.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-018",
    word: "apply for",
    meaning: "\u7533\u8acb",
    partOfSpeech: "v. phr.",
    example: "Several interns plan to apply for full-time jobs.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-019",
    word: "appoint",
    meaning: "\u4efb\u547d\uff1b\u6307\u5b9a",
    partOfSpeech: "v.",
    example: "The board will appoint a new director next month.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
  {
    id: "json-1-020",
    word: "appointment",
    meaning: "\u7d04\u6703\uff1b\u4efb\u547d",
    partOfSpeech: "n.",
    example: "I made an appointment with the sales manager.",
    tag: "\u532f\u5165\u55ae\u5b57",
  },
];

const existingImportedJson1Words = new Set(
  window.PDF_VOCAB_CARDS.map((card) => String(card.word || "").trim().toLowerCase()),
);

window.PDF_VOCAB_CARDS = [
  ...window.PDF_VOCAB_CARDS,
  ...IMPORTED_JSON_1_CARDS.filter(
    (card) => !existingImportedJson1Words.has(card.word.trim().toLowerCase()),
  ),
];
