window.VOCAB_PRONUNCIATION = {
  "a as well as b": { kk: "[e] [əz] [wɛl] [əz] [bi]", speak: "A as well as B" },
  "a be followed by b": { kk: "[e] [bi] [ˋfɑlod] [baɪ] [bi]", speak: "A be followed by B" },
  "a and b alike": { kk: "[e] [ənd] [bi] [əˋlaɪk]", speak: "A and B alike" },
  "a complete line of": { kk: "[ə] [kəmˋplit] [laɪn] [əv]" },
  "a copy of": { kk: "[ə] [ˋkɑpɪ] [əv]" },
  "a couple of": { kk: "[ə] [ˋkʌpḷ] [əv]" },
  "a glass of": { kk: "[ə] [glæs] [əv]" },
  "a great deal": { kk: "[ə] [gret] [dil]" },
  "a great deal of": { kk: "[ə] [gret] [dil] [əv]" },
  "a large attendance": { kk: "[ə] [lɑrdʒ] [əˋtɛndəns]" },
  "a letter of gratitude": { kk: "[ə] [ˋlɛtɚ] [əv] [ˋgrætəˌtud]" },
  "a loaf of": { kk: "[ə] [lof] [əv]" },
  "a number of": { kk: "[ə] [ˋnʌmbɚ] [əv]" },
  "a piece of equipment": { kk: "[ə] [pis] [əv] [ɪˋkwɪpmənt]" },
  "a range of": { kk: "[ə] [rendʒ] [əv]" },
  "a selection of": { kk: "[ə] [səˋlɛkʃən] [əv]" },
  "a series of": { kk: "[ə] [ˋsɪriz] [əv]" },
  "a sheet of": { kk: "[ə] [ʃit] [əv]" },
  "a string of": { kk: "[ə] [strɪŋ] [əv]" },
  "a variety of": { kk: "[ə] [vəˋraɪətɪ] [əv]" },
  "various": { kk: "[ˋvɛrɪəs]" },
  "abandon": { kk: "[əˋbændən]" },
  "abate": { kk: "[əˋbet]" },
  "abbreviate": { kk: "[əˋbrivɪˌet]" },
  "ability": { kk: "[əˋbɪlətɪ]" },
  "aboard": { kk: "[əˋbord]" },
  "abolish": { kk: "[əˋbɑlɪʃ]" },
  "abridgment": { kk: "[əˋbrɪdʒmənt]" },
  "abruptly": { kk: "[əˋbrʌptlɪ]" },
  "absence": { kk: "[ˋæbsəns]" },
  "absolute": { kk: "[ˋæbsəˌlut]" },
  "absolutely": { kk: "[ˋæbsəˌlutlɪ]" },
  "absorbing": { kk: "[əbˋzorbɪŋ]" },
  "abstract": { kk: "[ˋæbstrækt]" },
  "abundant": { kk: "[əˋbʌndənt]" },
  "abundantly": { kk: "[əˋbʌndəntlɪ]" },
  "abuse": { kk: "[əˋbjus; əˋbjuz]" },
  "accelerate": { kk: "[ækˋsɛləˌret]" },
  "accept": { kk: "[əkˋsɛpt]" },
  "accept an award": { kk: "[əkˋsɛpt] [ən] [əˋwɔrd]" },
  "accept the offer": { kk: "[əkˋsɛpt] [ði] [ˋɔfɚ]" },
  "acceptable": { kk: "[əkˋsɛptəbḷ]" },
  "access": { kk: "[ˋæksɛs]" },
  "access road": { kk: "[ˋæksɛs] [rod]" },
  "access to": { kk: "[ˋæksɛs] [tu]" },
  "accessibility": { kk: "[əkˌsɛsəˋbɪlətɪ]" },
  "accessible": { kk: "[əkˋsɛsəbḷ]" },
  "accidentally": { kk: "[ˌæksəˋdɛntlɪ]" },
  "acclaim": { kk: "[əˋklem]" },
  "accommodate": { kk: "[əˋkɑməˌdet]" },
  "accommodation": { kk: "[əˌkɑməˋdeʃən]" },
  "accompany": { kk: "[əˋkʌmpənɪ]" },
  "accomplish": { kk: "[əˋkɑmplɪʃ]" },
  "accomplished": { kk: "[əˋkɑmplɪʃt]" },
  "accomplishment": { kk: "[əˋkɑmplɪʃmənt]" },
  "accordance": { kk: "[əˋkɔrdəns]" },
  "accordingly": { kk: "[əˋkɔrdɪŋlɪ]" },
  "according to": { kk: "[əˋkɔrdɪŋ] [tu]" },
  "account": { kk: "[əˋkaʊnt]" },
  "account payable": { kk: "[əˋkaʊnt] [ˋpeəbḷ]" },
  "accountable": { kk: "[əˋkaʊntəbḷ]" },
  "accountant": { kk: "[əˋkaʊntənt]" },
  "accounting": { kk: "[əˋkaʊntɪŋ]" },
  "accredit": { kk: "[əˋkrɛdɪt]" },
  "accrue": { kk: "[əˋkru]" },
  "accumulate": { kk: "[əˋkjumjəˌlet]" },
  "accuracy": { kk: "[ˋækjərəsɪ]" },
  "accurate": { kk: "[ˋækjərət]" },
  "accurately": { kk: "[ˋækjərətlɪ]" },
  "accuse": { kk: "[əˋkjuz]" },
  "accumulation": { kk: "[əˌkjumjəˋleʃən]" },
  "accustomed": { kk: "[əˋkʌstəmd]" },
  "achievable": { kk: "[əˋtʃivəbḷ]" },
  "achieve": { kk: "[əˋtʃiv]" },
  "achieve one's goal": { kk: "[əˋtʃiv] [wʌnz] [gol]" },
  "achievement": { kk: "[əˋtʃivmənt]" },
  "achiever": { kk: "[əˋtʃivɚ]" },
  "acknowledge": { kk: "[əkˋnɑlɪdʒ]" },
  "acquaint": { kk: "[əˋkwent]" },
  "acquaintance": { kk: "[əˋkwentəns]" },
  "acquire": { kk: "[əˋkwaɪr]" },
  "acquired": { kk: "[əˋkwaɪrd]" },
  "acquisition": { kk: "[ˌækwəˋzɪʃən]" },
  "across from": { kk: "[əˋkrɔs] [frəm]" },
  "across the street": { kk: "[əˋkrɔs] [ðə] [strit]" },
  "act": { kk: "[ækt]" },
  "acting": { kk: "[ˋæktɪŋ]" },
  "activate": { kk: "[ˋæktəˌvet]" },
  "active": { kk: "[ˋæktɪv]" },
  "actually": { kk: "[ˋæktʃʊəlɪ]" },
  "acute": { kk: "[əˋkjut]" },
  "adapt": { kk: "[əˋdæpt]" },
  "adaptability": { kk: "[əˌdæptəˋbɪlətɪ]" },
  "adaptable": { kk: "[əˋdæptəbḷ]" },
  "adapted": { kk: "[əˋdæptɪd]" },
  "add up to": { kk: "[æd] [ʌp] [tu]" },
  "added benefits": { kk: "[ˋædɪd] [ˋbɛnəfɪts]" },
  "addition": { kk: "[əˋdɪʃən]" },
  "additional": { kk: "[əˋdɪʃənḷ]" },
  "additional charge": { kk: "[əˋdɪʃənḷ] [tʃɑrdʒ]" },
  "additional fee": { kk: "[əˋdɪʃənḷ] [fi]" },
  "additionally": { kk: "[əˋdɪʃənəlɪ]" },
  "address": { kk: "[əˋdrɛs; ˋædrɛs]" },
  "address the audience": { kk: "[əˋdrɛs] [ði] [ˋɔdɪəns]" },
  "adept": { kk: "[əˋdɛpt]" },
  "adequate": { kk: "[ˋædəkwɪt]" },
  "adequately": { kk: "[ˋædəkwɪtlɪ]" },
  "adhere": { kk: "[ədˋhɪr]" },
  "adjacent": { kk: "[əˋdʒesənt]" },
  "adjourn": { kk: "[əˋdʒɝn]" },
  "adjournment": { kk: "[əˋdʒɝnmənt]" },
  "adjust": { kk: "[əˋdʒʌst]" },
  "sought after": { kk: "[sɔt] [ˋæftɚ]" },
  "extravagant": { kk: "[ɪkˋstrævəgənt]" },
  "go to extravagant lengths to do": { kk: "[go] [tu] [ɪkˋstrævəgənt] [lɛŋθs] [tu] [du]" },
  "collectively": { kk: "[kəˋlɛktɪvlɪ]" },
  "substantially": { kk: "[səbˋstænʃəlɪ]" },
  "expressively": { kk: "[ɪkˋsprɛsɪvlɪ]" },
  "be expected to do": { kk: "[bi] [ɪkˋspɛktɪd] [tu] [du]" },
  "imaginative": { kk: "[ɪˋmædʒənətɪv]" },
  "configuration": { kk: "[kənˌfɪgjəˋreʃən]" },
  "place an order": { kk: "[ples] [ən] [ˋɔrdɚ]" },
  "executive": { kk: "[ɪgˋzɛkjətɪv]" },
  "distinguish myself": { kk: "[dɪˋstɪŋgwɪʃ] [maɪˋsɛlf]" },
  "covet": { kk: "[ˋkʌvɪt]" },
  "lost and found office": { kk: "[lɔst] [ənd] [faʊnd] [ˋɔfɪs]" },
  "miserly": { kk: "[ˋmaɪzɚlɪ]" },
  "rallying point": { kk: "[ˋrælɪɪŋ] [pɔɪnt]" },
  "warden": { kk: "[ˋwɔrdn]" },
  "as a result of": { kk: "[æz] [ə] [rɪˋzʌlt] [əv]" },
  "merger": { kk: "[ˋmɝdʒɚ]" },
  "prospective": { kk: "[prəˋspɛktɪv]" },
  "take advantage of": { kk: "[tek] [ədˋvæntɪdʒ] [əv]" },
  "promotion": { kk: "[prəˋmoʃən]" },
  "emerge from": { kk: "[ɪˋmɝdʒ] [frəm]" },
  "conscientiousness": { kk: "[ˌkɑnʃɪˋɛnʃəsnɪs]" },
  "managing director": { kk: "[ˋmænɪdʒɪŋ] [dəˋrɛktɚ]" },
  "certainly unacceptable": { kk: "[ˋsɝtnlɪ] [ˌʌnəkˋsɛptəbḷ]" },
  "employment section": { kk: "[ɪmˋplɔɪmənt] [ˋsɛkʃən]" },
  "a clear description of": { kk: "[ə] [klɪr] [dɪˋskrɪpʃən] [əv]" },
  "result in": { kk: "[rɪˋzʌlt] [ɪn]" },
  "misleading": { kk: "[mɪsˋlidɪŋ]" },
  "want ad": { kk: "[wɑnt] [æd]" },
  "offence/offense against": { kk: "[əˋfɛns] [əˋgɛnst]", speak: "offense against" },
  "hardship": { kk: "[ˋhɑrdʃɪp]" },
  "community": { kk: "[kəˋmjunətɪ]" },
  "census": { kk: "[ˋsɛnsəs]" },
  "tick off": { kk: "[tɪk] [ɔf]" },
  "grant": { kk: "[grænt]" },
  "toll-free": { kk: "[ˋtolˋfri]" },
  "amid": { kk: "[əˋmɪd]" },
  "honor": { kk: "[ˋɑnɚ]" },
  "prestigious": { kk: "[prɛˋstɪdʒəs]" },
  "advocates": { kk: "[ˋædvəˌkets]" },
  "advocate": { kk: "[ˋædvəkət; ˋædvəˌket]" },
  "unprivileged": { kk: "[ʌnˋprɪvəlɪdʒd]" },
  "extravaganza": { kk: "[ɪkˌstrævəˋgænzə]" },
  "sustainable": { kk: "[səˋstenəbḷ]" },
  "improve": { kk: "[ɪmˋpruv]" },
  "confident": { kk: "[ˋkɑnfədənt]" },
};

Object.assign(window.VOCAB_PRONUNCIATION, {
  antique: { kk: "[ænˋtik]" },
  anymore: { kk: "[ˌɛnɪˋmɔr]" },
  apologize: { kk: "[əˋpɑləˌdʒaɪz]" },
  apparatus: { kk: "[ˌæpəˋrætəs]" },
  apparel: { kk: "[əˋpærəl]" },
  apparently: { kk: "[əˋpærəntlɪ]" },
  appeal: { kk: "[əˋpil]" },
  appealing: { kk: "[əˋpilɪŋ]" },
  appear: { kk: "[əˋpɪr]" },
  appearance: { kk: "[əˋpɪrəns]" },
  appetizer: { kk: "[ˋæpəˌtaɪzɚ]" },
  applaud: { kk: "[əˋplɔd]" },
  appliance: { kk: "[əˋplaɪəns]" },
  applicant: { kk: "[ˋæpləkənt]" },
  application: { kk: "[ˌæpləˋkeʃən]" },
  "application form": { kk: "[ˌæpləˋkeʃən] [fɔrm]" },
  apply: { kk: "[əˋplaɪ]" },
  "apply for": { kk: "[əˋplaɪ] [fɔr]" },
  appoint: { kk: "[əˋpɔɪnt]" },
  appointment: { kk: "[əˋpɔɪntmənt]" },
});
